__default__:
    num_cores: 1
    maxvmem: 4G
gene_level:
    num_cores: 1
    maxvmem: 20G
gene_level_rep:
    num_cores: 1
    maxvmem: 20G
estimate_counts:
    num_cores: 1
    maxvmem: 20G
peer:
    num_cores: 1
    maxvmem: 30G
transcript_level:
    num_cores: 1
    maxvmem: 20G
run_kalliso:
    num_cores: 1
    maxvmem: 6G
run_kalliso_rep:
    num_cores: 1
    maxvmem: 6G
